apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-ingress-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controllers
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |
        controller:
          ingressClass: "public"
          hostPort:
            enabled: true
          kind: DaemonSet
          metrics:
            enabled: false
          publishService:
            enabled: false
          service:
            enabled: false
          resources:
            limits:
              cpu: 100m
              memory: 90Mi
            requests:
              cpu: 100m
              memory: 90Mi
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true