apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: argocd/
    repoURL: https://github.com/arnydnd/argocd-tests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true