apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controllers
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controllers
  project: default
  source:
    path: ingress_controllers/
    repoURL: https://github.com/arnydnd/argocd-tests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true